project_id = "ublsnradzhfpqhunfqbn"

[functions.plaid]
verify_jwt = false

[functions.process-invoice]
verify_jwt = false

[functions.create-client-user]
verify_jwt = false

[functions.process-bank-statement]
verify_jwt = false

[functions.categorize-transactions]
verify_jwt = false

[functions.analyze-spending]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false
